title: An exploration of IT
email: JPScripter@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A blog of the things in Technology that interest me.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: JeffTheScripter
github_username:  JPScripter

show_downloads: false
google_analytics: UA-140023239-1
theme: jekyll-theme-slate

collections:
  presentations:
    output: true
    path: /presentations/
    title: Presentations